INSERT INTO programmedhousehold.category (category_id, name, meal, difficulty, sidedish) VALUES (1,'Pongal','BREAKFAST','HARD',0),
                              (2,'Poori','BREAKFAST','HARD',0),
                              (3,'Millets Dosa','BREAKFAST','MODERATE',0),
                              (4,'Dal Dosa','BREAKFAST','MODERATE',0),
                              (5,'Kanji','BREAKFAST','EASY',0),
                              (6,'Sandwich','BREAKFAST','MODERATE',0),
                              (7,'Salad','BREAKFAST','EASY',0),
                              (8,'Misc-B','BREAKFAST','EASY',0),
                              (9,'Idli-Gravy','BREAKFAST','EASY',0),
                              (10,'Upma','BREAKFAST','EASY',0),
                              (11,'Dosa','BREAKFAST','EASY',0),
                              (12,'Chutney','BREAKFAST','EASY',1),
                              (13,'Others','BREAKFAST','NA',0),
                              (14,'Misc-L','LUNCH','MODERATE',0),
                              (15,'Biryani','LUNCH','HARD',0),
                              (16,'VarietyRice','LUNCH','EASY',0),
                              (17,'LentilGravy','LUNCH','MODERATE',0),
                              (18,'TamarindGravy','LUNCH','MODERATE',0),
                              (19,'Pulao','LUNCH','MODERATE',0),
                              (20,'LegumesGravy','LUNCH','MODERATE',0),
                              (21,'Kootu','LUNCH','EASY',1),
                              (22,'Poriyal','LUNCH','EASY',1),
                              (23,'Fry','LUNCH','HARD',1),
                              (24,'Thogayal','LUNCH','NA',1),
                              (13,'Others','LUNCH','NA',0),
                              (25,'Pasta','DINNER','EASY',0),
                              (26,'Noodles','DINNER','EASY',0),
                              (27,'Paratha','DINNER','MODERATE',0),
                              (28,'Idli','DINNER','EASY',0),
                              (29,'ChapatiGravy','DINNER','MODERATE',0),
                              (10,'Upma','DINNER','EASY',0),
                              (11,'Dosa','DINNER','EASY',0),
                              (12,'Chutney','DINNER','EASY',1),
                              (13,'Others','DINNER','NA',0),
                              (30,'Soup','MISC','NA',0),
                              (31,'Juice','MISC','NA',0),
                              (32,'Snacks','MISC','NA',0),
                              (33,'ChickenGravy','LUNCH','HARD',0);
