    INSERT INTO programmedhousehold.`itemtype` (type_id, type, stock_unit,recipe_unit) VALUES (16,'Beverages','MILLILITER','TEASPOON'),
                                                                                  (18,'Cosmetics-liquid','MILLILITER','NA'),
                                                                                  (4,'Dairy-liquid','MILLILITER','CUP'),
                                                                                  (3,'Dal-(For batter/sidedish)','GRAM','CUP'),
                                                                                  (2,'Flour-(For batter)','GRAM','CUP'),
                                                                                  (11,'Fruits','GRAM','COUNT'),
                                                                                  (6,'Ground spices - (Masala Powder)','GRAM','TEASPOON'),
                                                                                  (12,'Whole spices - (including Biryani masala)','GRAM','COUNT'),
                                                                                  (17,'Hygiene','COUNT','NA'),
                                                                                  (10,'Instant Food Products','GRAM','COUNT'),
                                                                                  (22,'Ketchup','GRAM','TEASPOON'),
                                                                                  (1,'Legumes','GRAM','CUP'),
                                                                                  (14,'Meat&Poultry','GRAM','GRAM'),
                                                                                  (19,'Medicine','COUNT','NA'),
                                                                                  (13,'Nuts','GRAM','COUNT'),
                                                                                  (9,'Oil','MILLILITER','TABLESPOON'),
                                                                                  (21,'Other','NA','NA'),
                                                                                  (5,'Rice','GRAM','CUP'),
                                                                                  (23,'Sauce','GRAM','TEASPOON'),
                                                                                  (7,'Seasoning','GRAM','TEASPOON'),
                                                                                  (20,'Household Supplies (in count)','COUNT','NA'),
                                                                                  (15,'Vegetables by weight','GRAM','GRAM'),
                                                                                  (8,'Whole spices - (Seeds)','GRAM','TEASPOON'),
                                                                                  (24,'Cosmetics-Solid','COUNT','NA'),
                                                                                  (25,'Dairy-Solid','GRAM','TABLESPOON'),
                                                                                  (26,'Household Supplies-solid','GRAM','NA'),
                                                                                  (27,'Household Supplies-liquid','MILLILITER','NA'),
                                                                                  (28,'Dal (For frying)','GRAM','TABLESPOON'),
                                                                                  (29,'Vegetables by count','COUNT','COUNT');
