INSERT INTO programmedhousehold.itemtype (type_id, type) VALUES (1,'Legumes'),
                              (2,'Flour'),
                              (3,'Dal'),
                              (4,'Dairy'),
                              (5,'Rice'),
                              (6,'Ground spices - (Masala Powder)'),
                              (7,'Seasoning'),
                              (8,'Whole spices - (Seeds)'),
                              (9,'Oil'),
                              (10,'Instant Food Products'),
                              (11,'Fruits'),
                              (12,'Herbs-(Biryani Spices)'),
                              (13,'Nuts'),
                              (14,'Meat&Poultry'),
                              (15,'Vegetables'),
                              (16,'Beverages'),
                              (17,'Hygiene'),
                              (18,'Cosmetics'),
                              (19,'Medicine'),
                              (20,'Toiletries'),
                              (21,'Other'),
                              (22,'Ketchup'),
                              (23,'Sauce');
