INSERT INTO programmedhousehold.item (id,name,type_id,is_essential,item_stock_qty,unit,refill) VALUES (1,'Chickpeas-Brown',1,1,500,'GRAM',90),
                                                                                                      (2,'Chickpeas-White',1,0,150,'GRAM',0),
                                                                                                      (3,'Comb',18,1,3,'COUNT',180),
                                                                                                      (4,'Greanpeas',1,1,500,'GRAM',90),
                                                                                                      (5,'Cowpeas',1,1,500,'GRAM',90),
                                                                                                      (6,'Kidney beans-(Rajma)',1,0,150,'GRAM',0),
                                                                                                      (7,'Soy beans',1,0,150,'GRAM',0),
                                                                                                      (8,'Peanuts',1,1,500,'GRAM',90),
                                                                                                      (9,'Lima beans-(Mochai)',1,1,500,'GRAM',90),
                                                                                                      (10,'Wheat Flour',2,1,1,'KILOGRAM',30),
                                                                                                      (11,'Maida',2,0,100,'GRAM',0),
                                                                                                      (12,'Besan/Chickpea Flour-(Kadalai Maavu)',2,1,200,'GRAM',30),
                                                                                                      (13,'Baking powder',2,0,0,'GRAM',0),
                                                                                                      (14,'Rice Flour',2,1,500,'GRAM',60),
                                                                                                      (15,'Corn Flour',2,1,500,'GRAM',90),
                                                                                                      (16,'Urad dal - black',3,0,250,'GRAM',0),
                                                                                                      (17,'Urad dal Whole - white',3,1,250,'GRAM',30),
                                                                                                      (18,'Urad dal Split - white',3,1,250,'GRAM',30),
                                                                                                      (19,'Toor dal',3,1,500,'GRAM',30),
                                                                                                      (20,'Channa dal',3,1,250,'GRAM',30),
                                                                                                      (21,'Moong dal',3,1,500,'GRAM',30),
                                                                                                      (22,'Roasted Chana dal-(Pottu kadalai)',3,1,200,'GRAM',30),
                                                                                                      (23,'Curd',4,1,500,'MILLILITER',3),
                                                                                                      (24,'Milk',4,1,500,'MILLILITER',1),
                                                                                                      (25,'Paneer',4,1,200,'GRAM',30),
                                                                                                      (26,'Ghee',4,1,500,'MILLILITER',30),
                                                                                                      (27,'Butter',4,1,200,'GRAM',30),
                                                                                                      (28,'Cheese - Block',4,0,200,'GRAM',0),
                                                                                                      (29,'Cheese - Shredded',4,0,200,'GRAM',0),
                                                                                                      (30,'Cheese - Slice',4,0,200,'GRAM',0),
                                                                                                      (31,'Steamed Rice',5,1,2,'KILOGRAM',30),
                                                                                                      (32,'Raw Rice',5,1,250,'GRAM',30),
                                                                                                      (33,'Idli Dosa Rice',5,1,500,'GRAM',30),
                                                                                                      (34,'Basmati Rice',5,1,1,'KILOGRAM',30),
                                                                                                      (35,'Brown Basmati Rice',5,1,5,'KILOGRAM',50),
                                                                                                      (36,'Turmeric powder',6,1,100,'GRAM',30),
                                                                                                      (37,'Chilli powder',6,1,100,'GRAM',30),
                                                                                                      (38,'Coriander powder',6,1,200,'GRAM',30),
                                                                                                      (39,'Garam Masala',6,1,100,'GRAM',30),
                                                                                                      (40,'Kashmiri chilli powder',6,1,100,'GRAM',30),
                                                                                                      (41,'Channa masala',6,0,50,'GRAM',0),
                                                                                                      (42,'Biryani masala',6,0,50,'GRAM',0),
                                                                                                      (43,'Muttom masala',6,0,50,'GRAM',0),
                                                                                                      (44,'Chicken masala',6,1,100,'GRAM',60),
                                                                                                      (45,'Kuzhambu milagai powder',6,1,100,'GRAM',30),
                                                                                                      (46,'Cumin powder',6,1,50,'GRAM',30),
                                                                                                      (47,'Sambar powder',6,1,100,'GRAM',60),
                                                                                                      (48,'Cardamom powder',6,1,25,'GRAM',60),
                                                                                                      (49,'Asafoetida - Hing (Perungayam)',6,1,50,'GRAM',60),
                                                                                                      (50,'Chilli flakes',7,1,50,'GRAM',60),
                                                                                                      (51,'Oregano',7,1,50,'GRAM',60),
                                                                                                      (52,'Mixed herbs',7,1,50,'GRAM',60),
                                                                                                      (53,'Mustard seeds',8,1,200,'GRAM',30),
                                                                                                      (54,'Fenugreek seeds',8,1,50,'GRAM',30),
                                                                                                      (55,'Sesame seeds - Black',8,1,100,'GRAM',60),
                                                                                                      (56,'Sesame seeds - White',8,0,0,'GRAM',0),
                                                                                                      (57,'Dry red chilly',8,1,200,'GRAM',30),
                                                                                                      (58,'Coriander seeds',8,1,100,'GRAM',60),
                                                                                                      (59,'Cumin seeds',8,1,100,'GRAM',30),
                                                                                                      (60,'Pepper corns',8,1,200,'GRAM',30),
                                                                                                      (61,'Fennel seeds- Anise (Sombu)',8,1,50,'GRAM',30),
                                                                                                      (62,'Gingelly oil',9,1,1,'LITRE',30),
                                                                                                      (63,'Cooking oil',9,1,1,'LITRE',30),
                                                                                                      (64,'Coconut oil',9,1,250,'MILLILITRE',30),
                                                                                                      (65,'Olive oil',9,1,250,'MILLILITRE',90),
                                                                                                      (66,'Semiya',10,1,2,'COUNT',30),
                                                                                                      (67,'Rava',10,1,500,'GRAM',60),
                                                                                                      (68,'Wheat rava',10,1,500,'GRAM',60),
                                                                                                      (69,'Puttu',10,1,500,'GRAM',150),
                                                                                                      (70,'Pasta',10,1,1,'KILOGRAM',60),
                                                                                                      (71,'Noodles',10,1,0,'GRAM',30),
                                                                                                      (72,'Cereals',10,1,500,'GRAM',90),
                                                                                                      (73,'Apple',11,0,500,'GRAM',0),
                                                                                                      (74,'Orange',11,0,500,'GRAM',0),
                                                                                                      (75,'Pomegranate',11,0,500,'GRAM',0),
                                                                                                      (76,'Mango',11,0,500,'GRAM',0),
                                                                                                      (77,'Papaya',11,0,1,'COUNT',0),
                                                                                                      (78,'Pineapple',11,0,1,'COUNT',0),
                                                                                                      (79,'Watermelon',11,0,1,'COUNT',0),
                                                                                                      (80,'Grapes',11,0,250,'GRAM',0),
                                                                                                      (81,'Lemon',11,0,0,'COUNT',0),
                                                                                                      (82,'Banana',11,1,500,'GRAM',4),
                                                                                                      (83,'Avocado',11,0,0,'GRAM',0),
                                                                                                      (84,'Tamarind',8,1,200,'GRAM',30),
                                                                                                      (85,'Clove',12,1,25,'GRAM',90),
                                                                                                      (86,'Cinnamon',12,1,50,'GRAM',90),
                                                                                                      (87,'Cardamom',12,1,50,'GRAM',90),
                                                                                                      (88,'Star Anise',12,1,50,'GRAM',90),
                                                                                                      (89,'Kasuri Methi',12,1,50,'GRAM',90),
                                                                                                      (90,'Saffron',12,0,0,'GRAM',0),
                                                                                                      (91,'Bayleaf',12,1,25,'GRAM',30),
                                                                                                      (92,'Nutmeg',12,0,0,'GRAM',0),
                                                                                                      (93,'Almond',13,1,200,'GRAM',30),
                                                                                                      (94,'Cashew',13,1,200,'GRAM',30),
                                                                                                      (95,'Raisins',13,1,200,'GRAM',30),
                                                                                                      (96,'Pistachio',13,1,200,'GRAM',30),
                                                                                                      (97,'Dates',13,1,500,'GRAM',30),
                                                                                                      (98,'Walnut',13,1,200,'GRAM',30),
                                                                                                      (99,'Sunflower seeds',13,0,100,'GRAM',0),
                                                                                                      (100,'Pumpkin seeds',13,0,100,'GRAM',0),
                                                                                                      (101,'Flax seeds',13,0,100,'GRAM',0),
                                                                                                      (102,'Chicken',14,0,300,'GRAM',0),
                                                                                                      (103,'Mutton',14,0,0,'GRAM',0),
                                                                                                      (104,'Fish',14,0,0,'GRAM',0),
                                                                                                      (105,'Egg',14,1,12,'COUNT',7),
                                                                                                      (106,'Curry leaves',15,1,1,'PACK',7),
                                                                                                      (107,'Coriander leaves',15,1,1,'PACK',7),
                                                                                                      (108,'Onion',15,1,2,'KILOGRAM',7),
                                                                                                      (109,'Tomato',15,1,2,'KILOGRAM',7),
                                                                                                      (110,'Ginger',15,1,100,'GRAM',14),
                                                                                                      (111,'Garlic',15,1,200,'GRAM',14),
                                                                                                      (112,'Green chilly',15,1,200,'GRAM',14),
                                                                                                      (113,'Mint leaves',15,0,1,'PACK',0),
                                                                                                      (114,'Brinjal',15,0,250,'GRAM',0),
                                                                                                      (115,'Drumstick',15,0,2,'COUNT',0),
                                                                                                      (116,'Carrot',15,0,250,'GRAM',0),
                                                                                                      (117,'Beetroot',15,0,250,'GRAM',0),
                                                                                                      (118,'Potato',15,0,250,'GRAM',0),
                                                                                                      (119,'Sweet potato',15,0,500,'GRAM',0),
                                                                                                      (120,'Raw banana/Plantain - (Vaalai kaai)',15,0,2,'COUNT',0),
                                                                                                      (121,'Banana/Plantain stem - (Vaalai thandu)',15,0,1,'COUNT',0),
                                                                                                      (122,'Banana/Plantain flower - (Vaalai poo)',15,0,1,'COUNT',0),
                                                                                                      (123,'Cauliflower',15,0,1,'COUNT',0),
                                                                                                      (124,'Mushroom',15,0,1,'PACK',0),
                                                                                                      (125,'Beans',15,0,250,'GRAM',0),
                                                                                                      (126,'Cabbage',15,0,1,'COUNT',0),
                                                                                                      (127,'Broccoli',15,0,1,'COUNT',0),
                                                                                                      (128,'Capsicum',15,0,1,'COUNT',0),
                                                                                                      (129,'Bottle gourd - (Surakkai)',15,0,1,'COUNT',0),
                                                                                                      (130,'Chayote - (Chow chow)',15,0,1,'COUNT',0),
                                                                                                      (131,'Snake gourd - (Pudalangai)',15,0,1,'COUNT',0),
                                                                                                      (132,'Ash gourd - (White pumpkin)',15,0,250,'GRAM',0),
                                                                                                      (133,'Pumpkin',15,0,250,'GRAM',0),
                                                                                                      (134,'Elephant foot yam - (Senai Kizhangu)',15,0,200,'GRAM',0),
                                                                                                      (135,'Small yams - (Karunai Kizhangu)',15,0,200,'GRAM',0),
                                                                                                      (136,'Small onion',15,1,250,'GRAM',14),
                                                                                                      (137,'Filter Coffee',16,1,500,'GRAM',30),
                                                                                                      (138,'Tea',16,1,100,'GRAM',60),
                                                                                                      (139,'Horlicks',16,0,0,'GRAM',0),
                                                                                                      (140,'Boost',16,0,0,'GRAM',0),
                                                                                                      (141,'Complan',16,0,0,'GRAM',0),
                                                                                                      (142,'Green Tea',16,1,100,'GRAM',60),
                                                                                                      (143,'Instant Coffee',16,0,0,'GRAM',0),
                                                                                                      (144,'Tomato ketchup',22,1,200,'GRAM',60),
                                                                                                      (145,'Condom',17,1,1,'PACK',60),
                                                                                                      (146,'Sanitizer',17,1,200,'MILLILITER',30),
                                                                                                      (147,'Hair serum',18,1,200,'MILLILITER',30),
                                                                                                      (148,'Hair oil',18,1,200,'MILLILITER',30),
                                                                                                      (149,'Eye liner',18,1,1,'COUNT',90),
                                                                                                      (150,'Kajal',18,1,1,'COUNT',60),
                                                                                                      (152,'Lipstick',18,1,1,'COUNT',30),
                                                                                                      (153,'Sticker',18,1,3,'PACK',150),
                                                                                                      (154,'Moisturizer',18,1,250,'MILLILITER',30),
                                                                                                      (155,'Toner',18,1,100,'MILLILITER',30),
                                                                                                      (156,'Perfume',18,1,50,'MILLILITER',180),
                                                                                                      (157,'Fever',19,1,0,'COUNT',180),
                                                                                                      (158,'Gastritis',19,1,0,'COUNT',180),
                                                                                                      (159,'Cold',19,1,0,'COUNT',180),
                                                                                                      (160,'Running nose',19,1,0,'COUNT',180),
                                                                                                      (161,'Cough',19,1,0,'COUNT',180),
                                                                                                      (162,'Eucalyptus capsules',19,1,0,'COUNT',180),
                                                                                                      (163,'Contraceptive pill',19,1,0,'PACK',30),
                                                                                                      (164,'Face tissue',20,1,1,'PACK',30),
                                                                                                      (165,'Kitchen tissue',20,1,1,'PACK',30),
                                                                                                      (166,'Garbage cover',20,1,1,'PACK',30),
                                                                                                      (167,'Toilet cleaner',20,1,1,'LITER',60),
                                                                                                      (168,'Floor cleaner',20,1,1,'LITER',30),
                                                                                                      (169,'Tooth paste',20,1,250,'GRAM',30),
                                                                                                      (170,'Body wash',20,1,300,'MILLILITER',30),
                                                                                                      (171,'Tongue cleaner',20,1,1,'COUNT',90),
                                                                                                      (172,'Shampoo',20,1,250,'MILLILITER',90),
                                                                                                      (173,'Conditioner',20,1,250,'MILLILITER',90),
                                                                                                      (174,'Mouth wash',20,0,0,'MILLILITER',0),
                                                                                                      (175,'Air freshner',20,1,2,'PACK',30),
                                                                                                      (176,'Green chilli sauce',23,1,200,'GRAM',90),
                                                                                                      (177,'Red chilli sauce',23,1,200,'GRAM',90),
                                                                                                      (178,'Soy sauce',23,1,200,'GRAM',90),
                                                                                                      (179,'Sanitary Pad XL',17,1,1,'PACK',30),
                                                                                                      (180,'Sanitary Pad Regular',17,1,1,'PACK',30),
                                                                                                      (181,'Panty Liner',17,1,1,'PACK',30),
                                                                                                      (182,'Moong bean-(green gram)',1,1,500,'GRAM',90),
                                                                                                      (183,'Sugar',21,1,500,'GRAM',60),
                                                                                                      (184,'Salt',21,1,500,'GRAM',60),
                                                                                                      (185,'Water',21,1,0,'CUP',0),
                                                                                                      (186,'Coconut',15,1,1,'COUNT',7),
                                                                                                      (187,'GingerGarlicPaste',6,1,100,'GRAM',30);







