INSERT INTO programmedhousehold.`item` (id,name,item_stock_qty,type_id) VALUES (1,'Chickpeas-Brown',250,1),
                                                                               (2,'Chickpeas-White',250,1),
                                                                               (3,'Comb',3,24),
                                                                               (4,'Greanpeas',250,1),
                                                                               (5,'Cowpeas',250,1),
                                                                               (6,'Kidney beans-(Rajma)',250,1),
                                                                               (7,'Soy beans',250,1),
                                                                               (8,'Peanuts',250,1),
                                                                               (9,'Lima beans-(Mochai)',250,1),
                                                                               (10,'Wheat Flour',1000,2),
                                                                               (11,'Maida',100,2),
                                                                               (12,'Besan/Chickpea Flour-(Kadalai Maavu)',200,2),
                                                                               (13,'Baking powder',100,21),
                                                                               (14,'Rice Flour',500,2),
                                                                               (15,'Corn Flour',500,2),
                                                                               (16,'Urad dal - black',250,3),
                                                                               (17,'Urad dal Whole - white',250,3),
                                                                               (18,'Urad dal Split - white',250,28),
                                                                               (19,'Toor dal',500,3),
                                                                               (20,'Channa dal - (Frying)',100,28),
                                                                               (21,'Moong dal',500,3),
                                                                               (22,'Roasted Chana dal-(Pottu kadalai)',200,28),
                                                                               (23,'Curd',500,4),
                                                                               (24,'Milk',500,4),
                                                                               (25,'Paneer',200,25),
                                                                               (26,'Ghee',500,9),
                                                                               (27,'Butter',200,25),
                                                                               (28,'Cheese - Block',200,25),
                                                                               (29,'Cheese - Shredded',200,25),
                                                                               (30,'Cheese - Slice',200,25),
                                                                               (31,'Steamed Rice',2000,5),
                                                                               (32,'Raw Rice',250,5),
                                                                               (33,'Idli Dosa Rice',500,5),
                                                                               (34,'Basmati Rice',1000,5),
                                                                               (35,'Brown Basmati Rice',5000,5),
                                                                               (36,'Turmeric powder',100,6),
                                                                               (37,'Chilli powder',100,6),
                                                                               (38,'Coriander powder',200,6),
                                                                               (39,'Garam Masala',100,6),
                                                                               (40,'Kashmiri chilli powder',100,6),
                                                                               (41,'Channa masala',50,6),
                                                                               (42,'Biryani masala',50,6),
                                                                               (43,'Muttom masala',50,6),
                                                                               (44,'Chicken masala',100,6),
                                                                               (45,'Kuzhambu milagai powder',100,6),
                                                                               (46,'Cumin powder',50,6),
                                                                               (47,'Sambar powder',100,6),
                                                                               (48,'Cardamom powder',25,6),
                                                                               (49,'Asafoetida - Hing (Perungayam)',50,6),
                                                                               (50,'Chilli flakes',50,7),
                                                                               (51,'Oregano',50,7),
                                                                               (52,'Mixed herbs',50,7),
                                                                               (53,'Mustard seeds',200,8),
                                                                               (54,'Fenugreek seeds',50,8),
                                                                               (55,'Sesame seeds - Black',100,8),
                                                                               (56,'Sesame seeds - White',100,8),
                                                                               (57,'Dry red chilly',200,12),
                                                                               (58,'Coriander seeds',100,8),
                                                                               (59,'Cumin seeds',100,8),
                                                                               (60,'Pepper corns',200,8),
                                                                               (61,'Fennel seeds- Anise (Sombu)',50,8),
                                                                               (62,'Gingelly oil',1000,9),
                                                                               (63,'Cooking oil',1000,9),
                                                                               (64,'Coconut oil',250,9),
                                                                               (65,'Olive oil',250,9),
                                                                               (66,'Semiya',1,10),
                                                                               (67,'Rava',500,10),
                                                                               (68,'Wheat rava',500,10),
                                                                               (69,'Puttu',500,10),
                                                                               (70,'Pasta',1,10),
                                                                               (71,'Noodles',300,10),
                                                                               (72,'Cereals',500,10),
                                                                               (73,'Apple',500,11),
                                                                               (74,'Orange',500,11),
                                                                               (75,'Pomegranate',500,11),
                                                                               (76,'Mango',500,11),
                                                                               (77,'Papaya',1,11),
                                                                               (78,'Pineapple',1,11),
                                                                               (79,'Watermelon',1,11),
                                                                               (80,'Grapes',250,11),
                                                                               (81,'Lemon',2,11),
                                                                               (82,'Banana',500,11),
                                                                               (83,'Avocado',2,11),
                                                                               (84,'Tamarind',200,8),
                                                                               (85,'Clove',25,12),
                                                                               (86,'Cinnamon',50,12),
                                                                               (87,'Cardamom',50,12),
                                                                               (88,'Star Anise',50,12),
                                                                               (89,'Kasuri Methi',50,12),
                                                                               (90,'Saffron',25,12),
                                                                               (91,'Bayleaf',25,12),
                                                                               (92,'Nutmeg',50,12),
                                                                               (93,'Almond',200,13),
                                                                               (94,'Cashew',200,13),
                                                                               (95,'Raisins',200,13),
                                                                               (96,'Pistachio',200,13),
                                                                               (97,'Dates',500,13),
                                                                               (98,'Walnut',200,13),
                                                                               (99,'Sunflower seeds',100,13),
                                                                               (100,'Pumpkin seeds',100,13),
                                                                               (101,'Flax seeds',100,13),
                                                                               (102,'Chicken',300,14),
                                                                               (103,'Mutton',250,14),
                                                                               (104,'Fish',250,14),
                                                                               (105,'Egg',12,14),
                                                                               (106,'Curry leaves',1,15),
                                                                               (107,'Coriander leaves',1,15),
                                                                               (108,'Onion',2,29),
                                                                               (109,'Tomato',2,29),
                                                                               (110,'Ginger',100,15),
                                                                               (111,'Garlic',200,15),
                                                                               (112,'Green chilly',200,29),
                                                                               (113,'Mint leaves',1,15),
                                                                               (114,'Brinjal',250,29),
                                                                               (115,'Drumstick',2,29),
                                                                               (116,'Carrot',250,15),
                                                                               (117,'Beetroot',250,15),
                                                                               (118,'Potato',250,15),
                                                                               (119,'Sweet potato',500,15),
                                                                               (120,'Raw banana/Plantain - (Vaalai kaai)',2,29),
                                                                               (121,'Banana/Plantain stem - (Vaalai thandu)',1,29),
                                                                               (122,'Banana/Plantain flower - (Vaalai poo)',1,29),
                                                                               (123,'Cauliflower',1,29),
                                                                               (124,'Mushroom',1,15),
                                                                               (125,'Beans',250,15),
                                                                               (126,'Cabbage',1,29),
                                                                               (127,'Broccoli',1,29),
                                                                               (128,'Capsicum',1,29),
                                                                               (129,'Bottle gourd - (Surakkai)',1,29),
                                                                               (130,'Chayote - (Chow chow)',1,29),
                                                                               (131,'Snake gourd - (Pudalangai)',1,29),
                                                                               (132,'Ash gourd - (White pumpkin)',250,15),
                                                                               (133,'Pumpkin',250,15),
                                                                               (134,'Elephant foot yam - (Senai Kizhangu)',200,15),
                                                                               (135,'Small yams - (Karunai Kizhangu)',200,15),
                                                                               (136,'Small onion',250,15),
                                                                               (137,'Filter Coffee',500,16),
                                                                               (138,'Tea',100,16),
                                                                               (139,'Horlicks',0,16),
                                                                               (140,'Boost',0,16),
                                                                               (141,'Complan',0,16),
                                                                               (142,'Green Tea',100,16),
                                                                               (143,'Instant Coffee',0,16),
                                                                               (144,'Tomato ketchup',200,22),
                                                                               (145,'Condom',1,17),
                                                                               (146,'Sanitizer',200,17),
                                                                               (147,'Hair serum',200,18),
                                                                               (148,'Hair oil',200,18),
                                                                               (149,'Eye liner',1,24),
                                                                               (150,'Kajal',1,24),
                                                                               (152,'Lipstick',1,24),
                                                                               (153,'Sticker',3,24),
                                                                               (154,'Moisturizer',250,18),
                                                                               (155,'Toner',100,18),
                                                                               (156,'Perfume',50,18),
                                                                               (157,'Fever',10,19),
                                                                               (158,'Gastritis',10,19),
                                                                               (159,'Cold',10,19),
                                                                               (160,'Running nose',10,19),
                                                                               (161,'Cough',10,19),
                                                                               (162,'Eucalyptus capsules',10,19),
                                                                               (163,'Contraceptive pill',21,19),
                                                                               (164,'Face tissue',1,20),
                                                                               (165,'Kitchen tissue',1,20),
                                                                               (166,'Garbage cover',1,20),
                                                                               (167,'Toilet cleaner',1,27),
                                                                               (168,'Floor cleaner',1,27),
                                                                               (169,'Tooth paste',250,26),
                                                                               (170,'Body wash',300,27),
                                                                               (171,'Tongue cleaner',1,20),
                                                                               (172,'Shampoo',250,27),
                                                                               (173,'Conditioner',250,27),
                                                                               (174,'Mouth wash',250,27),
                                                                               (175,'Air freshner',2,26),
                                                                               (176,'Green chilli sauce',200,23),
                                                                               (177,'Red chilli sauce',200,23),
                                                                               (178,'Soy sauce',200,23),
                                                                               (179,'Sanitary Pad XL',15,17),
                                                                               (180,'Sanitary Pad Regular',15,17),
                                                                               (181,'Panty Liner',20,17),
                                                                               (182,'Moong bean-(green gram)',500,1),
                                                                               (183,'Sugar',500,21),
                                                                               (184,'Salt',500,21),
                                                                               (185,'Water',0,21),
                                                                               (186,'Coconut',2,15),
                                                                               (187,'GingerGarlicPaste',100,6),
                                                                               (188,'Channa dal - (Dosa Batter/Side dish)',250,3);
