INSERT INTO programmedhousehold.`item` (id,name,item_stock_qty,type_id,stock_unit,recipe_unit)  VALUES (1,'Chickpeas-Brown',250,1,'GRAM','CUP'),
                                                                                                       (2,'Chickpeas-White',250,1,'GRAM','CUP'),
                                                                                                       (3,'Comb',3,18,'NA','NA'),
                                                                                                       (4,'Greanpeas',250,1,'GRAM','CUP'),
                                                                                                       (5,'Cowpeas',250,1,'GRAM','CUP'),
                                                                                                       (6,'Kidney beans-(Rajma)',250,1,'GRAM','CUP'),
                                                                                                       (7,'Soy beans',250,1,'GRAM','CUP'),
                                                                                                       (8,'Peanuts',250,1,'GRAM','CUP'),
                                                                                                       (9,'Lima beans-(Mochai)',250,1,'GRAM','CUP'),
                                                                                                       (10,'Wheat Flour',1000,2,'GRAM','CUP'),
                                                                                                       (11,'Maida',100,2,'GRAM','CUP'),
                                                                                                       (12,'Besan/Chickpea Flour-(Kadalai Maavu)',200,2,'GRAM','CUP'),
                                                                                                       (13,'Baking powder',100,21,'GRAM','TEASPOON'),
                                                                                                       (14,'Rice Flour',500,2,'GRAM','CUP'),
                                                                                                       (15,'Corn Flour',500,2,'GRAM','CUP'),
                                                                                                       (16,'Urad dal - black',250,3,'GRAM','CUP'),
                                                                                                       (17,'Urad dal Whole - white',250,3,'GRAM','CUP'),
                                                                                                       (18,'Urad dal Split - white',250,3,'GRAM','TABLESPOON'),
                                                                                                       (19,'Toor dal',500,3,'GRAM','CUP'),
                                                                                                       (20,'Channa dal - (Frying)',100,3,'GRAM','TABLESPOON'),
                                                                                                       (21,'Moong dal',500,3,'GRAM','CUP'),
                                                                                                       (22,'Roasted Chana dal-(Pottu kadalai)',200,3,'GRAM','TABLESPOON'),
                                                                                                       (23,'Curd',500,4,'GRAM','CUP'),
                                                                                                       (24,'Milk',500,4,'GRAM','CUP'),
                                                                                                       (25,'Paneer',200,25,'GRAM','GRAM'),
                                                                                                       (26,'Ghee',500,9,'GRAM','TABLESPOON'),
                                                                                                       (27,'Butter',200,25,'GRAM','TABLESPOON'),
                                                                                                       (28,'Cheese - Block',200,25,'GRAM','TABLESPOON'),
                                                                                                       (29,'Cheese - Shredded',200,25,'GRAM','TABLESPOON'),
                                                                                                       (30,'Cheese - Slice',200,25,'GRAM','COUNT'),
                                                                                                       (31,'Steamed Rice',2000,5,'GRAM','CUP'),
                                                                                                       (32,'Raw Rice',250,5,'GRAM','CUP'),
                                                                                                       (33,'Idli Dosa Rice',500,5,'GRAM','CUP'),
                                                                                                       (34,'Basmati Rice',1000,5,'GRAM','CUP'),
                                                                                                       (35,'Brown Basmati Rice',5000,5,'GRAM','CUP'),
                                                                                                       (36,'Turmeric powder',100,6,'GRAM','TEASPOON'),
                                                                                                       (37,'Chilli powder',100,6,'GRAM','TEASPOON'),
                                                                                                       (38,'Coriander powder',200,6,'GRAM','TEASPOON'),
                                                                                                       (39,'Garam Masala',100,6,'GRAM','TEASPOON'),
                                                                                                       (40,'Kashmiri chilli powder',100,6,'GRAM','TEASPOON'),
                                                                                                       (41,'Channa masala',50,6,'GRAM','TEASPOON'),
                                                                                                       (42,'Biryani masala',50,6,'GRAM','TEASPOON'),
                                                                                                       (43,'Muttom masala',50,6,'GRAM','TEASPOON'),
                                                                                                       (44,'Chicken masala',100,6,'GRAM','TEASPOON'),
                                                                                                       (45,'Kuzhambu milagai powder',100,6,'GRAM','TEASPOON'),
                                                                                                       (46,'Cumin powder',50,6,'GRAM','TEASPOON'),
                                                                                                       (47,'Sambar powder',100,6,'GRAM','TEASPOON'),
                                                                                                       (48,'Cardamom powder',25,6,'GRAM','TEASPOON'),
                                                                                                       (49,'Asafoetida - Hing (Perungayam)',50,6,'GRAM','TEASPOON'),
                                                                                                       (50,'Chilli flakes',50,22,'GRAM','TEASPOON'),
                                                                                                       (51,'Oregano',50,22,'GRAM','TEASPOON'),
                                                                                                       (52,'Mixed herbs',50,22,'GRAM','TEASPOON'),
                                                                                                       (53,'Mustard seeds',200,8,'GRAM','TEASPOON'),
                                                                                                       (54,'Fenugreek seeds',50,8,'GRAM','TEASPOON'),
                                                                                                       (55,'Sesame seeds - Black',100,8,'GRAM','TEASPOON'),
                                                                                                       (56,'Sesame seeds - White',100,8,'GRAM','TEASPOON'),
                                                                                                       (57,'Dry red chilly',200,12,'GRAM','COUNT'),
                                                                                                       (58,'Coriander seeds',100,8,'GRAM','TEASPOON'),
                                                                                                       (59,'Cumin seeds',100,8,'GRAM','TEASPOON'),
                                                                                                       (60,'Pepper corns',200,8,'GRAM','TEASPOON'),
                                                                                                       (61,'Fennel seeds- Anise (Sombu)',50,8,'GRAM','TEASPOON'),
                                                                                                       (62,'Gingelly oil',1000,9,'GRAM','TABLESPOON'),
                                                                                                       (63,'Cooking oil',1000,9,'GRAM','TABLESPOON'),
                                                                                                       (64,'Coconut oil',250,9,'GRAM','TABLESPOON'),
                                                                                                       (65,'Olive oil',250,9,'GRAM','TABLESPOON'),
                                                                                                       (66,'Semiya',1,10,'COUNT','COUNT'),
                                                                                                       (67,'Rava',500,10,'GRAM','CUP'),
                                                                                                       (68,'Wheat rava',500,10,'GRAM','CUP'),
                                                                                                       (69,'Puttu',500,10,'GRAM','CUP'),
                                                                                                       (70,'Pasta',1,10,'GRAM','CUP'),
                                                                                                       (71,'Noodles',300,10,'GRAM','GRAM'),
                                                                                                       (72,'Cereals',500,10,'GRAM','CUP'),
                                                                                                       (73,'Apple',500,11,'GRAM','COUNT'),
                                                                                                       (74,'Orange',500,11,'GRAM','COUNT'),
                                                                                                       (75,'Pomegranate',500,11,'GRAM','COUNT'),
                                                                                                       (76,'Mango',500,11,'GRAM','COUNT'),
                                                                                                       (77,'Papaya',1,11,'COUNT','COUNT'),
                                                                                                       (78,'Pineapple',1,11,'COUNT','COUNT'),
                                                                                                       (79,'Watermelon',1,11,'COUNT','COUNT'),
                                                                                                       (80,'Grapes',250,11,'GRAM','GRAM'),
                                                                                                       (81,'Lemon',2,11,'COUNT','COUNT'),
                                                                                                       (82,'Banana',500,11,'COUNT','COUNT'),
                                                                                                       (83,'Avocado',2,11,'COUNT','COUNT'),
                                                                                                       (84,'Tamarind',200,8,'GRAM','TABLESPOON'),
                                                                                                       (85,'Clove',25,12,'GRAM','COUNT'),
                                                                                                       (86,'Cinnamon',50,12,'GRAM','COUNT'),
                                                                                                       (87,'Cardamom',50,12,'GRAM','COUNT'),
                                                                                                       (88,'Star Anise',50,12,'GRAM','COUNT'),
                                                                                                       (89,'Kasuri Methi',50,12,'GRAM','COUNT'),
                                                                                                       (90,'Saffron',25,12,'GRAM','TEASPOON'),
                                                                                                       (91,'Bay-leaf',25,12,'GRAM','COUNT'),
                                                                                                       (92,'Nutmeg',50,12,'GRAM','TEASPOON'),
                                                                                                       (93,'Almond',200,13,'GRAM','COUNT'),
                                                                                                       (94,'Cashew',200,13,'GRAM','COUNT'),
                                                                                                       (95,'Raisins',200,13,'GRAM','COUNT'),
                                                                                                       (96,'Pistachio',200,13,'GRAM','COUNT'),
                                                                                                       (97,'Dates',500,13,'GRAM','COUNT'),
                                                                                                       (98,'Walnut',200,13,'GRAM','COUNT'),
                                                                                                       (99,'Sunflower seeds',100,13,'GRAM','TEASPOON'),
                                                                                                       (100,'Pumpkin seeds',100,13,'GRAM','TEASPOON'),
                                                                                                       (101,'Flax seeds',100,13,'GRAM','TEASPOON'),
                                                                                                       (102,'Chicken',300,14,'GRAM','GRAM'),
                                                                                                       (103,'Mutton',250,14,'GRAM','GRAM'),
                                                                                                       (104,'Fish',250,14,'GRAM','GRAM'),
                                                                                                       (105,'Egg',12,28,'COUNT','COUNT'),
                                                                                                       (106,'Curry leaves',1,15,'PACK','FEW'),
                                                                                                       (107,'Coriander leaves',1,15,'PACK','FEW'),
                                                                                                       (108,'Onion',2,7,'GRAM','COUNT'),
                                                                                                       (109,'Tomato',2,7,'GRAM','COUNT'),
                                                                                                       (110,'Ginger',100,7,'GRAM','TEASPOON'),
                                                                                                       (111,'Garlic',200,7,'GRAM','COUNT'),
                                                                                                       (112,'Green chilly',50,7,'GRAM','COUNT'),
                                                                                                       (113,'Mint leaves',1,15,'PACK','FEW'),
                                                                                                       (114,'Brinjal',6,7,'COUNT','COUNT'),
                                                                                                       (115,'Drumstick',2,7,'COUNT','COUNT'),
                                                                                                       (116,'Carrot',5,7,'COUNT','COUNT'),
                                                                                                       (117,'Beetroot',2,7,'COUNT','COUNT'),
                                                                                                       (118,'Potato',6,7,'COUNT','COUNT'),
                                                                                                       (119,'Sweet potato',500,7,'GRAM','GRAM'),
                                                                                                       (120,'Raw banana/Plantain - (Vaalai kaai)',2,7,'GRAM','GRAM'),
                                                                                                       (121,'Banana/Plantain stem - (Vaalai thandu)',1,7,'GRAM','GRAM'),
                                                                                                       (122,'Banana/Plantain flower - (Vaalai poo)',1,7,'GRAM','GRAM'),
                                                                                                       (123,'Cauliflower',1,7,'COUNT','COUNT'),
                                                                                                       (124,'Mushroom',1,7,'GRAM','GRAM'),
                                                                                                       (125,'Beans',250,7,'GRAM','COUNT'),
                                                                                                       (126,'Cabbage',1,7,'COUNT','COUNT'),
                                                                                                       (127,'Broccoli',1,7,'COUNT','COUNT'),
                                                                                                       (128,'Capsicum',1,7,'COUNT','COUNT'),
                                                                                                       (129,'Bottle gourd - (Surakkai)',1,7,'GRAM','GRAM'),
                                                                                                       (130,'Chayote - (Chow chow)',1,7,'COUNT','COUNT'),
                                                                                                       (131,'Snake gourd - (Pudalangai)',1,7,'GRAM','GRAM'),
                                                                                                       (132,'Ash gourd - (White pumpkin)',250,7,'GRAM','GRAM'),
                                                                                                       (133,'Pumpkin',250,7,'GRAM','GRAM'),
                                                                                                       (134,'Elephant foot yam - (Senai Kizhangu)',200,7,'GRAM','GRAM'),
                                                                                                       (135,'Small yams - (Karunai Kizhangu)',200,7,'GRAM','GRAM'),
                                                                                                       (136,'Small onion',250,7,'GRAM','COUNT'),
                                                                                                       (137,'Filter Coffee',500,16,'GRAM','TEASPOON'),
                                                                                                       (138,'Tea',100,16,'GRAM','TEASPOON'),
                                                                                                       (139,'Horlicks',0,16,'GRAM','TEASPOON'),
                                                                                                       (140,'Boost',0,16,'GRAM','TEASPOON'),
                                                                                                       (141,'Complan',0,16,'GRAM','TEASPOON'),
                                                                                                       (142,'Green Tea',100,16,'GRAM','COUNT'),
                                                                                                       (143,'Instant Coffee',0,16,'GRAM','TEASPOON'),
                                                                                                       (144,'Tomato ketchup',200,23,'GRAM','TEASPOON'),
                                                                                                       (145,'Condom',1,17,'COUNT','NA'),
                                                                                                       (146,'Sanitizer',200,17,'MILLILITER','NA'),
                                                                                                       (147,'Hair serum',200,18,'MILLILITER','NA'),
                                                                                                       (148,'Hair oil',200,18,'MILLILITER','NA'),
                                                                                                       (149,'Eye liner',1,18,'MILLILITER','NA'),
                                                                                                       (150,'Kajal',1,18,'GRAM','NA'),
                                                                                                       (152,'Lipstick',1,18,'GRAM','NA'),
                                                                                                       (153,'Sticker',3,18,'COUNT','NA'),
                                                                                                       (154,'Moisturizer',250,18,'GRAM','NA'),
                                                                                                       (155,'Toner',100,18,'MILLILITER','NA'),
                                                                                                       (156,'Perfume',50,18,'MILLILITER','NA'),
                                                                                                       (157,'Fever',10,19,'COUNT','NA'),
                                                                                                       (158,'Gastritis',10,19,'COUNT','NA'),
                                                                                                       (159,'Cold',10,19,'COUNT','NA'),
                                                                                                       (160,'Running nose',10,19,'COUNT','NA'),
                                                                                                       (161,'Cough',10,19,'COUNT','NA'),
                                                                                                       (162,'Eucalyptus capsules',10,19,'COUNT','NA'),
                                                                                                       (163,'Contraceptive pill',21,19,'COUNT','NA'),
                                                                                                       (164,'Face tissue',1,26,'COUNT','NA'),
                                                                                                       (165,'Kitchen tissue',1,20,'COUNT','NA'),
                                                                                                       (166,'Garbage cover',1,20,'COUNT','NA'),
                                                                                                       (167,'Toilet cleaner',1,20,'LITRE','NA'),
                                                                                                       (168,'Floor cleaner',1,20,'MILLILITER','NA'),
                                                                                                       (169,'Tooth paste',250,26,'GRAM','NA'),
                                                                                                       (170,'Body wash',300,26,'MILLILITER','NA'),
                                                                                                       (171,'Tongue cleaner',1,26,'COUNT','NA'),
                                                                                                       (172,'Shampoo',250,26,'MILLILITER','NA'),
                                                                                                       (173,'Conditioner',250,26,'MILLILITER','NA'),
                                                                                                       (174,'Mouth wash',250,26,'MILLILITER','NA'),
                                                                                                       (175,'Air freshner',2,20,'GRAM','NA'),
                                                                                                       (176,'Green chilli sauce',200,23,'GRAM','NA'),
                                                                                                       (177,'Red chilli sauce',200,23,'GRAM','NA'),
                                                                                                       (178,'Soy sauce',200,23,'GRAM','NA'),
                                                                                                       (179,'Sanitary Pad XL',15,17,'COUNT','NA'),
                                                                                                       (180,'Sanitary Pad Regular',15,17,'COUNT','NA'),
                                                                                                       (181,'Panty Liner',20,17,'COUNT','NA'),
                                                                                                       (182,'Moong bean-(green gram)',500,1,'GRAM','CUP'),
                                                                                                       (183,'Sugar',500,22,'GRAM','TEASPOON'),
                                                                                                       (184,'Salt',500,22,'GRAM','TEASPOON'),
                                                                                                       (185,'Water',0,27,'MILLILITER','CUP'),
                                                                                                       (186,'Coconut',2,7,'COUNT','CUP'),
                                                                                                       (187,'GingerGarlicPaste',100,23,'GRAM','TEASPOON'),
                                                                                                       (188,'Channa dal - (Dosa Batter/Side dish)',250,3,'GRAM','CUP'),
                                                                                                       (189,'Honey',500,22,'GRAM','TEASPOON'),
                                                                                                       (190,'Frozen Green peas',500,7,'GRAM','CUP'),
                                                                                                       (191,'Sweetcorn kernels',500,7,'GRAM','CUP');

