INSERT INTO  programmedhousehold.recipe (category_id,title,reference,instructions,prep_time) VALUES (1,'Ven Pongal','https://hebbarskitchen.com/ven-pongal-recipe-khara-pongal/',NULL,1),
                                                                                                    (1,'Rava Pongal','https://www.youtube.com/watch?v=X_5yZbKSiPw',NULL,3),
                                                                                                    (2,'Wheat Poori-Channa masala','https://holycowvegan.net/chana-masala/#recipe',NULL,2),
                                                                                                    (2,'Ragi Poori-Potato masala','https://www.youtube.com/watch?v=AyLUOV6Qo9I',NULL,4),
                                                                                                    (2,'Aloo Poori-Green peas masala','https://www.youtube.com/watch?v=nRtByV-Jt7s&t=10s',NULL,5),
                                                                                                    (3,'Wheat Dosa-Onion chutney','https://www.youtube.com/watch?v=tFOFUKPwLpI',NULL,1),
                                                                                                    (3,'Kambu Dosa-Garlic chutney','https://www.yummytummyaarthi.com/instant-kambu-dosa-recipe/',NULL,3),
                                                                                                    (3,'Ragi Dosa-Tomato chutney','https://hebbarskitchen.com/instant-ragi-dosa-recipe-finger-millet/',NULL,5),
                                                                                                    (3,'Rava Dosa-Onion Garlic chutney','https://hebbarskitchen.com/instant-rava-dosa-recipe-suji-ka-dosa/',NULL,7),
                                                                                                    (4,'Muzhu Uzhundhu Dosa-Onion tomato chutney','rice 0.5, urad dal 0.5',NULL,2),
                                                                                                    (4,'Ada Dosa-Coconut chutney','rice (1.5) , channa dal(0.5), urad dal(0.75), toor dal(0.25), moong dal(0.25)',NULL,4),
                                                                                                    (4,'Chickpea Dosa-Red chilli spicy chutney','2 tumbler rice + 1 tumbler chickpea',NULL,6),
                                                                                                    (4,'Pesarattu Dosa-Ginger chutney','https://hebbarskitchen.com/pesarattu-recipe-moong-dal-dosa-recipe/',NULL,8),
                                                                                                    (5,'Rava khichdi','https://www.youtube.com/watch?v=iaO5_T-3t7A',NULL,1),
                                                                                                    (5,'Semiya khichdi','https://www.youtube.com/watch?v=lLGCF9fugKI',NULL,2),
                                                                                                    (5,'Sabudhana khichdi','https://www.youtube.com/watch?v=SE4Dc0XyhV8',NULL,3),
                                                                                                    (5,'Oats khichdi','https://www.vegrecipesofindia.com/oats-khichdi-recipe/#wprm-recipe-container-156705',NULL,4),
                                                                                                    (6,'Bread omelette','https://www.youtube.com/watch?v=7ZHWY4Lm-aE',NULL,1),
                                                                                                    (6,'Veg sandwich','https://www.youtube.com/watch?v=N_QvR7lQxp8',NULL,2),
                                                                                                    (6,'Potato sandwich','https://www.youtube.com/watch?v=9rixiRulNX4',NULL,3),
                                                                                                    (6,'Sweetcorn sandwich','https://www.youtube.com/watch?v=syamzXY0YUs',NULL,4),
                                                                                                    (7,'Green gram sprout salad','https://www.instagram.com/p/C1b90DaB6x7/?igsh=MXdrdHpzNThwMGhrZw==',NULL,1),
                                                                                                    (7,'Chick peas sprout salad','https://www.instagram.com/p/C1b90DaB6x7/?igsh=MXdrdHpzNThwMGhrZw==',NULL,2),
                                                                                                    (7,'Cow pea/Lobia salad','https://www.instagram.com/p/C1b90DaB6x7/?igsh=MXdrdHpzNThwMGhrZw==',NULL,3),
                                                                                                    (7,'Mung sprout sweet corn salad','https://aromaticessence.co/healthy-mung-sprouts-sweet-corn-salad/',NULL,4),
                                                                                                    (8,'Puttu - Kadala curry','https://hebbarskitchen.com/kadala-curry-recipe-puttu-kadala-curry/',NULL,1),
                                                                                                    (8,'Idiyappam','https://www.vegrecipesofindia.com/idiyappam-recipe-nool-puttu/',NULL,2),
                                                                                                    (8,'Aapam','https://www.youtube.com/watch?v=1Nx08cxacww&list=RDCMUCG3B5UDD0rgEgKrpn1hZz3w&index=40',NULL,3),
                                                                                                    (8,'Rava Idly-gravy','https://www.youtube.com/watch?v=DneHAcV-PAo',NULL,4),
                                                                                                    (9,'Tomato sambar','https://www.youtube.com/watch?v=ve86eNh13Ns&t=192s',NULL,1),
                                                                                                    (9,'Moong dal sambar','https://www.youtube.com/watch?v=r6kJ1O7d-k8',NULL,2),
                                                                                                    (9,'Brinjal kichadi','https://www.chitrasfoodbook.com/2009/04/kathirikai-khichidi-brinjal-gravy-for.html',NULL,3),
                                                                                                    (9,'Sorakkai kadayal','https://www.youtube.com/watch?v=mVNUtod7aMA',NULL,4),
                                                                                                    (9,'Chickpea flour gravy','https://www.youtube.com/watch?v=vIuyohZ2Y2g',NULL,5),
                                                                                                    (10,'Khuska with Chicken changezi','https://www.youtube.com/watch?v=4GdVa-49iEg',NULL,1),
                                                                                                    (10,'Coconut milk rice with Hariyali chicken','https://www.youtube.com/watch?v=4-ocKf9haBk',NULL,4),
                                                                                                    (10,'Khuska with Butter chicken','https://www.youtube.com/watch?v=RKNogWbAivY',NULL,7),
                                                                                                    (11,'Broccoli fried rice','https://www.youtube.com/watch?v=ijUl4nx0PPw',NULL,1),
                                                                                                    (11,'Chinese fried rice','https://www.youtube.com/watch?v=LPv_C1CaZjA',NULL,2),
                                                                                                    (11,'Veg fried rice','https://www.youtube.com/watch?v=Ng5GQbmF5iE',NULL,3),
                                                                                                    (11,'Malaysian fried rice','https://www.youtube.com/watch?v=Rjh83rxIHcE',NULL,4),
                                                                                                    (11,'Singapore fried rice','https://www.youtube.com/watch?v=m2ksi39B9rA',NULL,5),
                                                                                                    (12,'Jeera rice with Mushroom gravy',NULL,NULL,2),
                                                                                                    (12,'Ghee rice with Soya gravy',NULL,NULL,5),
                                                                                                    (13,'Rasam - Bitter gourd aviyal','https://www.youtube.com/watch?v=3-E70r2UFQg',NULL,1),
                                                                                                    (13,'Rasam - Appala kootu','https://www.youtube.com/watch?v=dew9LY079O4',NULL,2),
                                                                                                    (13,'Rasam - Vendakkai pachadi','https://www.youtube.com/watch?v=cNPP5OKmBE8',NULL,3),
                                                                                                    (13,'Rasam - Tomato pachadi','https://www.youtube.com/watch?v=m2ZcguPCFuc',NULL,4),
                                                                                                    (14,'Poricha Kuzhambu','https://www.youtube.com/watch?v=7GgaSWI1Gic',NULL,1),
                                                                                                    (14,'Mor Kuzhambu','https://www.youtube.com/watch?v=X7ijhIWMxHs',NULL,2),
                                                                                                    (14,'Urundai Kuzhambu','https://www.youtube.com/watch?v=eAcSEPjqI4Q',NULL,3),
                                                                                                    (14,'Sodhi','https://www.subbuskitchen.com/sodhi/',NULL,4),
                                                                                                    (15,'Egg Biryani - Shorba','https://www.youtube.com/watch?v=W2_55u8ZJjw',NULL,NULL),
                                                                                                    (15,'Chicken Biryani - Shorba','https://www.youtube.com/watch?v=y4YuC0_-RFQ',NULL,3),
                                                                                                    (15,'Chettinad Style Mushroom/Egg Biryani - Shorba','https://www.kannammacooks.com/chettinad-mushroom-biryani/',NULL,6),
                                                                                                    (16,'Lemon rice-Coconut thogayal','https://www.youtube.com/watch?v=w0gZ5xvmOAk',NULL,1),
                                                                                                    (16,'Coconut rice-Malli thogayal','https://hebbarskitchen.com/coconut-rice-recipe-nariyal-chawal/',NULL,2),
                                                                                                    (16,'Puliyogare-Porikadalai thogayal','https://www.youtube.com/watch?v=kDaTl1oDkng&list=RDCMUCG3B5UDD0rgEgKrpn1hZz3w&index=16',NULL,3),
                                                                                                    (16,'Tomato rice-Pudina thogayal','https://www.indianveggiedelight.com/instant-pot-tomato-rice/',NULL,4),
                                                                                                    (17,'Sambar-Poriyal',NULL,NULL,1),
                                                                                                    (17,'Kootan soru','https://www.youtube.com/watch?v=Iz54ktM0Abc',NULL,2),
                                                                                                    (17,'Idi Sambar-Aviyal','https://www.kowsisfoodbook.com/2015/08/nellai-idi-sambar.html',NULL,3),
                                                                                                    (17,'Uzhundhu sadam-Ellu thogayal','https://www.yummytummyaarthi.com/ulundu-choru-recipe-ulundhu-saadam/',NULL,4),
                                                                                                    (18,'Chinna vengaya khuzambu','https://www.youtube.com/watch?v=WzNRVucTSzk',NULL,1),
                                                                                                    (18,'Kara khuzambu','https://www.kannammacooks.com/chettinad-kara-kuzhambu-kara-kulambu-recipe/',NULL,2),
                                                                                                    (18,'Poondu khuzambu','https://revisfoodography.com/2015/02/poondu-kuzhambu-garlic-gravy/',NULL,3),
                                                                                                    (18,'Theeyal','https://www.kannammacooks.com/ulli-theeyal-recipe/',NULL,4),
                                                                                                    (19,'White sauce pasta','https://www.youtube.com/watch?v=7FGSClllWCc&t=378s',NULL,1),
                                                                                                    (19,'Red sauce pasta','https://www.youtube.com/watch?v=7FGSClllWCc&t=378s',NULL,2),
                                                                                                    (19,'Indian style macroni pasta','https://www.youtube.com/watch?v=7FGSClllWCc&t=378s',NULL,3),
                                                                                                    (19,'Chinese pasta','https://www.youtube.com/watch?v=7FGSClllWCc&t=378s',NULL,4),
                                                                                                    (19,'Pink sauce pasta','https://www.youtube.com/watch?v=kNm5wUlvDUQ',NULL,5),
                                                                                                    (20,'Soupy Noodles',NULL,NULL,1),
                                                                                                    (20,'Cream of mushroom soup','https://www.barleyandsage.com/homemade-cream-of-mushroom-soup/#ingredient-notes',NULL,2),
                                                                                                    (20,'Sweet potato soup','https://www.instagram.com/p/CzOQ9MLJLBY/?igsh=MWgyNG10NzhlMGNrNQ%3D%3D&img_index=1',NULL,3),
                                                                                                    (20,'Butternut squash soup','https://www.instagram.com/p/CzOQ9MLJLBY/?igsh=MWgyNG10NzhlMGNrNQ%3D%3D&img_index=1',NULL,4),
                                                                                                    (20,'Broccoli cheddar soup','https://www.instagram.com/p/CzL535OOA5g/?igsh=MWxmbm5zZmc0N3V5OA%3D%3D',NULL,5),
                                                                                                    (21,'Aloo paratha','https://www.indianhealthyrecipes.com/aloo-paratha/',NULL,1),
                                                                                                    (21,'Onion paratha','https://www.archanaskitchen.com/spicy-onion-stuffed-parathas',NULL,2),
                                                                                                    (21,'Chilli paratha','https://www.youtube.com/watch?v=Lv35hF-mqGs',NULL,3),
                                                                                                    (21,'Paneer paratha','https://www.youtube.com/watch?v=5cJ_LmnIYTs',NULL,4),
                                                                                                    (22,'Onion coconut roasted gram dal garlic red chilli','https://www.youtube.com/watch?v=_lZ1QDmN2bY',NULL,1),
                                                                                                    (22,'Onion tomato roasted gram dal garlic red chilli','https://www.youtube.com/watch?v=B2TBiED9K0o',NULL,2),
                                                                                                    (22,'Onion tomato garlic red chilli','https://www.youtube.com/watch?v=19kniR39qlg',NULL,3),
                                                                                                    (22,'Coconut roasted gram dal ginger green chilli','https://www.youtube.com/watch?v=EDLaisq59Ac',NULL,4),
                                                                                                    (23,'Onion tomato thokku','https://www.youtube.com/watch?v=PISDJ_uaAuE',NULL,1),
                                                                                                    (23,'Paneer burji','https://www.youtube.com/watch?v=vFgf0v0zgas',NULL,2),
                                                                                                    (23,'White kurma','https://rakskitchen.net/vellai-kurma-recipe-white-kurma-without-tomato/',NULL,3),
                                                                                                    (23,'Tomato kurma','https://www.youtube.com/watch?v=VtRtwGJ3tzo',NULL,4),
                                                                                                    (23,'black bean gravy','https://www.instagram.com/reel/C1r3JaUPD8P/?igsh=MWZwczFzNG5mYnRqMQ==',NULL,5),
                                                                                                    (23,'Dal tadka','https://www.youtube.com/watch?v=mLvvcs9S0Z0',NULL,6),
                                                                                                    (24,'Corn flour cheela','https://www.instagram.com/reel/C2SHS_tvo8P/?igsh=MWVpOWNjd290bTdyeg==',NULL,1),
                                                                                                    (24,'Suji cheela','https://youtube.com/shorts/E4gNiEeHKVY?si=0fjEN5yCfj5eNXa9',NULL,2),
                                                                                                    (24,'Oats cheela','https://youtube.com/shorts/zJeKNG1BUdA?si=JD2NEsdTvPuo7Q1p',NULL,3),
                                                                                                    (24,'Poha cheela','https://youtube.com/shorts/CeFcwHUgxi8?si=FJ2qqb3DVVcxo9dr',NULL,4),
                                                                                                    (25,'Mint chutney','https://www.youtube.com/watch?v=BnSOcl85rHM',NULL,1),
                                                                                                    (25,'Mint Coriander chutney','https://www.youtube.com/watch?v=UyNV1EAcxxM',NULL,2),
                                                                                                    (25,'Tomato Coriander chutney','https://www.youtube.com/watch?v=_3ZTma_qFWg',NULL,3),
                                                                                                    (25,'Tomato peanut chutney','https://www.youtube.com/watch?v=kqsCak5awXE',NULL,4),
                                                                                                    (26,'Raw banana fry','https://www.youtube.com/watch?v=_-EpVC9uRHs',NULL,NULL),
                                                                                                    (26,'Bitter gourd fry','https://www.youtube.com/watch?v=ZnoBvQI8aaE',NULL,NULL),
                                                                                                    (26,'Brinjal fry','https://www.youtube.com/watch?v=VgYOjjqAs54',NULL,NULL),
                                                                                                    (26,'Elephant yam fry','https://www.youtube.com/watch?v=UMIQJHreekU',NULL,NULL),
                                                                                                    (27,'Kothamalli thogayal','https://www.youtube.com/watch?v=iUQbra2BS9I',NULL,NULL),
                                                                                                    (27,'Porikadalai thogayal','https://www.youtube.com/watch?v=K5-ttLw8n-8',NULL,NULL),
                                                                                                    (27,'Coconut thogayal','https://www.youtube.com/watch?v=TnSV4uEIbRY',NULL,NULL),
                                                                                                    (27,'Pudina thogayal','https://www.youtube.com/watch?v=IRfFYSTBBvc',NULL,NULL),
                                                                                                    (28,'Chow chow kootu','https://www.youtube.com/watch?v=FfKWf7SgrEg',NULL,NULL),
                                                                                                    (28,'Bottle gourd kootu','https://www.youtube.com/watch?v=lQSDQqOGG1Q',NULL,NULL),
                                                                                                    (28,'Snake gourd kootu','https://www.youtube.com/watch?v=7Nc2z7jwF5U',NULL,NULL),
                                                                                                    (28,'Ash gourd kootu','https://www.youtube.com/watch?v=z531frhuxFo',NULL,NULL),
                                                                                                    (29,'Carrot poriyal','https://www.youtube.com/watch?v=2lr_dGTX4GU',NULL,NULL),
                                                                                                    (29,'Beetroot poriyal',NULL,NULL,NULL),
                                                                                                    (29,'Beans poriyal','https://urbanfarmie.com/beans-poriyal/',NULL,NULL),
                                                                                                    (29,'Raw banana puttu','https://www.yummytummyaarthi.com/valakai-puttu-podimas-raw-plantain-with/',NULL,NULL),
                                                                                                    (29,'Cauliflower poriyal','https://www.youtube.com/watch?v=7UQQqjxd5-c',NULL,NULL),
                                                                                                    (29,'Cabbage poriyal',NULL,NULL,NULL),
                                                                                                    (29,'Bitter gourd poriyal','https://www.youtube.com/watch?v=oBg87w6HZFY',NULL,NULL),
                                                                                                    (29,'Potato poriyal','https://www.youtube.com/watch?v=E-pS5ZAto0g',NULL,NULL),
                                                                                                    (29,'Sweet potato poriyal','https://www.youtube.com/watch?v=s4fbB3PyYB4',NULL,NULL),
                                                                                                    (30,'Ginger chutney','https://hebbarskitchen.com/ginger-chutney-recipe-allam-pachadi/#recipe_card_for_ginger_chutney_recipe',NULL,NULL),
                                                                                                    (30,'Garlic chutney','https://www.youtube.com/watch?v=zMw1amrhHds',NULL,NULL),
                                                                                                    (30,'tomato chutney','https://hebbarskitchen.com/tangy-tomato-chutney-recipe-idli-dosa/#Recipe_Card_for_tamatar_ki_chutney',NULL,NULL),
                                                                                                    (30,'Onion garlic chutney','https://www.vidhyashomecooking.com/onion-chutney/#recipe',NULL,NULL),
                                                                                                    (30,'Onion tomato chutney','https://www.cookingandme.com/onion-tomato-chutney-recipe-idli-dosa/#recipe',NULL,NULL),
                                                                                                    (30,'Red chilli spicy chutney','https://www.cookingandme.com/red-chilli-chutney-recipe-no-coconut/#recipe',NULL,NULL),
                                                                                                    (31,'Kuththu parupu kanji',NULL,NULL,NULL),
                                                                                                    (32,'Thai Pongal','https://www.youtube.com/watch?v=jiKDWXIptPA&list=RDCMUCG3B5UDD0rgEgKrpn1hZz3w&start_radio=1&rv=jiKDWXIptPA&t=3',NULL,NULL),
                                                                                                    (32,'Thai Poosam','https://www.youtube.com/watch?v=4a8v_SF79wU&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=23&pp=iAQB',NULL,NULL),
                                                                                                    (32,'Maha Shivaratri','https://www.youtube.com/watch?v=EzoWPrCfEy4&pp=ygUaeW9nYW1iYWwgc3VuZGFyIHNoaXZhcmF0cmk%3D',NULL,NULL),
                                                                                                    (32,'Thiruvadhirai','https://www.youtube.com/watch?v=caFc10tR-j8&list=RDCMUCG3B5UDD0rgEgKrpn1hZz3w&index=34',NULL,NULL),
                                                                                                    (32,'Chithirai Visu','https://www.youtube.com/watch?v=audO2roJBEs&pp=ygUdeW9nYW1iYWwgc3VuZGFyIGNoaXRpcmFpIHZpc3U%3D',NULL,NULL),
                                                                                                    (32,'Chitra pournami','https://www.youtube.com/watch?v=7zoZsydr2-I&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=1',NULL,NULL),
                                                                                                    (32,'Akshaya Tritiya','https://www.youtube.com/watch?v=Y5KM10z3l3w&pp=ygUfeW9nYW1iYWwgc3VuZGFyIGFrc2hheWEgdHJpdGl5YQ%3D%3D',NULL,NULL),
                                                                                                    (32,'Vaikasi Visakam','https://www.youtube.com/watch?v=0S0NcCPs_Nk',NULL,NULL),
                                                                                                    (32,'Aadi Perukku','https://www.youtube.com/watch?v=SnMZvVY54rc',NULL,NULL),
                                                                                                    (32,'Aadi Amavasai','https://www.youtube.com/watch?v=ESUYexaiTHw&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=3',NULL,NULL),
                                                                                                    (32,'Aadi Pooram','https://www.youtube.com/watch?v=LljW2xTf3U0&pp=ygUcYWFkaSBwZXJ1a2t1IHlvZ2FtYmFsIHN1bmRhcg%3D%3D',NULL,NULL),
                                                                                                    (32,'Varalakshmi vratam','https://www.youtube.com/watch?v=uFogpqVI1-M&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=7',NULL,NULL),
                                                                                                    (32,'Aavani avitam','https://www.youtube.com/watch?v=azurAsZdzPk',NULL,NULL),
                                                                                                    (32,'Onam','https://www.youtube.com/watch?v=ImQGa7D-4NI&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=14&pp=iAQB',NULL,NULL),
                                                                                                    (32,'Krishna jayanthi','https://www.youtube.com/watch?v=5wgRbZK7geI&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=9',NULL,NULL),
                                                                                                    (32,'Vinayaga Chaturthi','https://www.youtube.com/watch?v=oY3e1gkaJF8&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=13',NULL,NULL),
                                                                                                    (32,'Navratri-day1','https://www.youtube.com/watch?v=xnWw3aE2Rzw&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=37',NULL,NULL),
                                                                                                    (32,'Navratri-day2','https://www.youtube.com/watch?v=aWY8K1p_otg&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=38',NULL,NULL),
                                                                                                    (32,'Navratri-day3','https://www.youtube.com/watch?v=XlI2GlCjfBc&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=39',NULL,NULL),
                                                                                                    (32,'Navratri-day4','https://www.youtube.com/watch?v=ER36lxxmItM',NULL,NULL),
                                                                                                    (32,'Navratri-day5','https://www.youtube.com/watch?v=AUK_nDSOql4',NULL,NULL),
                                                                                                    (32,'Navratri-day6','https://www.youtube.com/watch?v=udJEJcXGlRk&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=40',NULL,NULL),
                                                                                                    (32,'Navratri-day7','https://www.youtube.com/watch?v=xxlYdzY0o1I&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=41',NULL,NULL),
                                                                                                    (32,'Navratri-day8','https://www.youtube.com/watch?v=C1rDzO1A2ow&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=42',NULL,NULL),
                                                                                                    (32,'Navratri-day9','https://www.youtube.com/watch?v=Dso5G7eCwTM&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=15',NULL,NULL),
                                                                                                    (32,'Purattasi sanikizhamai','https://www.youtube.com/watch?v=Xefw-cmo6HQ',NULL,NULL),
                                                                                                    (32,'Vijayadhashami',NULL,NULL,NULL),
                                                                                                    (32,'Skanda shashti','https://www.youtube.com/watch?v=530fNSMEz0w&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=17&pp=iAQB',NULL,NULL),
                                                                                                    (32,'Dwadashi paranai','https://www.youtube.com/watch?v=sI9UapCh8PE&pp=ygUieW9nYW1iYWwgc3VuZGFyIHZhaWt1bnRhIGVrYWRhc2hpIA%3D%3D',NULL,NULL),
                                                                                                    (32,'Vaikunta ekadasi','https://www.youtube.com/watch?v=8b0t3cGRMiU&pp=ygUieW9nYW1iYWwgc3VuZGFyIHZhaWt1bnRhIGVrYWRhc2hpIA%3D%3D',NULL,NULL),
                                                                                                    (32,'Deepavali','https://www.youtube.com/watch?v=keHuvpkrFYU&pp=ygUleW9nYW1iYWwgc3VuZGFyIHZpamF5YWRhc2hhbWkgcmVjaXBlcw%3D%3D',NULL,NULL),
                                                                                                    (32,'Karthigai Deepam','https://www.youtube.com/watch?v=7MCerN2myGs&list=PLa3a5O_Lwkf4YfEUIt8ULAUfbO6Neu5pi&index=18&pp=iAQB',NULL,NULL),
                                                                                                    (32,'New year',NULL,NULL,NULL),
                                                                                                    (32,'Christmas','https://www.youtube.com/watch?v=Shbs0MRAvb4&pp=ygUZY2hyaXN0bWFzIHlvZ2FtYmFsIHN1bmRhcg%3D%3D',NULL,NULL),
                                                                                                    (32,'Avira Birthday',NULL,NULL,NULL),
                                                                                                    (32,'Pappa Birthday',NULL,NULL,NULL),
                                                                                                    (32,'My Birthday',NULL,NULL,NULL),
                                                                                                    (32,'Wedding Anniversary',NULL,NULL,NULL),
                                                                                                    (37,'Leftover - Breakfast',NULL,NULL,NULL),
                                                                                                    (37,'Leftover - Lunch',NULL,NULL,NULL),
                                                                                                    (37,'Leftover - Dinner',NULL,NULL,NULL);


