version: '3.9'
services:
  mysql-db:
    image: container-registry.oracle.com/mysql/community-server:8.2
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: programmedhousehold
      MYSQL_USER: phuser
      MYSQL_PASSWORD: phpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ph-net
    healthcheck:
      test: [ "CMD", "/healthcheck.sh" ]
      timeout: 5s
      retries: 50

  backend:
    build:
      context: ./programmed-household-backend
      dockerfile: Dockerfile
      target: backend-img
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/programmedhousehold
      SPRING_DATASOURCE_USERNAME: phuser
      SPRING_DATASOURCE_PASSWORD: phpassword
      SPRING_DATASOURCE_HIKARI_DDL_AUTO: none
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-sSf", "http://backend:5000/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ph-net

  ui-nginx-server:
    container_name: ui-nginx-server
    build:
      context: ./programmed-household-ui
      dockerfile: Dockerfile
      target: ph-nginx-img
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ph-net

volumes:
  mysql-data: {}

networks:
  ph-net:
    driver: bridge