/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package srinageswari.programmedhousehold.coreservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;

/**
 * @author smanickavasagam
 */
@SpringBootApplication(
    exclude = {SecurityAutoConfiguration.class, ManagementWebSecurityAutoConfiguration.class})
public class CoreServiceApplication {
  public static void main(String[] args) {
    SpringApplication.run(CoreServiceApplication.class, args);
  }
}
