INSERT INTO programmedhousehold.category (category_id, name, meal, day, difficulty, sidedish)
VALUES (1, 'Pongal', 'BREAKFAST', 'SUNDAY', 'HARD', 0),
       (2, 'Poori', 'BREAKFAST', 'SUNDAY', 'HARD', 0),
       (3, 'Millets Dosa', 'BREAKFAST', 'MONDAY', 'MODERATE', 0),
       (4, 'Dal Dosa', 'BREAKFAST', 'MONDAY', 'MODERATE', 0),
       (5, 'Kichadi', 'BREAKFAST', 'TUESDAY', 'EASY', 0),
       (6, 'Sandwich', 'BREAKFAST', 'FRIDAY', 'MODERATE', 0),
       (7, 'Smoothie-Salad', 'BREAKFAST', 'WEDNESDAY', 'MODERATE', 0),
       (8, 'Misc-B', 'BREAKFAST', 'SATURDAY', 'EASY', 0),
       (9, 'Idli-gravy', 'BREAKFAST', 'THURSDAY', 'EASY', 1),
       (10, 'Non-vegGravy', 'LUNCH', 'SATURDAY', 'HARD', 1),
       (11, 'FriedRice', 'LUNCH', 'TUESDAY', 'MODERATE', 0),
       (12, 'VegGravy', 'LUNCH', 'SATURDAY', 'MODERATE', 1),
       (13, 'Rasam', 'LUNCH', 'MONDAY', 'MODERATE', 1),
       (14, 'Misc-L', 'LUNCH', 'SUNDAY', 'MODERATE', 1),
       (15, 'Biryani', 'LUNCH', 'SATURDAY', 'HARD', 0),
       (16, 'VarietyRice', 'LUNCH', 'THURSDAY', 'EASY', 0),
       (17, 'Dal Based Recipe', 'LUNCH', 'WEDNESDAY', 'HARD', 0),
       (18, 'TamarindGravy', 'LUNCH', 'FRIDAY', 'MODERATE', 1),
       (19, 'Pasta', 'DINNER', 'TUESDAY', 'EASY', 0),
       (20, 'Soups&Noodles meal', 'DINNER', 'SUNDAY', 'EASY', 0),
       (21, 'Paratha', 'DINNER', 'MONDAY', 'MODERATE', 0),
       (22, 'Idli-Chutney', 'DINNER', 'SATURDAY', 'EASY', 1),
       (23, 'ChapatiGravy', 'DINNER', 'THURSDAY', 'MODERATE', 1),
       (24, 'Cheela', 'DINNER', 'WEDNESDAY', 'EASY', 0),
       (25, 'Dosa-Chutney', 'DINNER', 'FRIDAY', 'EASY', 1),
       (26, 'Fry', 'LUNCH', 'NA', 'NA', 1),
       (27, 'Thogayal', 'LUNCH', 'NA', 'NA', 1),
       (28, 'Kootu', 'LUNCH', 'NA', 'NA', 1),
       (29, 'Poriyal', 'LUNCH', 'NA', 'NA', 1),
       (30, 'Spicy-Chutney', 'MISC', 'NA', 'NA', 1),
       (31, 'Kanji', 'BREAKFAST', 'NA', 'NA', 0),
       (32, 'Special Occasions', 'MISC', 'NA', 'NA', 0),
       (33, 'Soups', 'MISC', 'NA', 'NA', 0),
       (34, 'Juice', 'MISC', 'NA', 'NA', 0),
       (35, 'Snacks', 'MISC', 'NA', 'NA', 0),
       (36, 'Starters', 'MISC', 'NA', 'NA', 0);


