/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package srinageswari.programmedhousehold;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @author smanickavasagam
 */
@SpringBootApplication
// @SpringBootApplication(exclude = {SecurityAutoConfiguration.class,
// ManagementWebSecurityAutoConfiguration.class})
public class CoreServiceApplication {
  public static void main(String[] args) {
    SpringApplication.run(CoreServiceApplication.class, args);
  }
}
